### ISSUE TITLE
哥

### ISSUE THREAD

**Issue by zengjiapei3000** [TimeBeneficiary/ParameciaAndroidReverse#1]
如

**Comment by TensorFu** [comment]
> 如题，没接触过这个方向

我接触这个也比较少，你看看这个链接
[参考链接](https://blog.csdn.net/lixpjita39/article/details/89424459)

**Comment by TimeBeneficiary** [comment]
> 如题，没接触过这个方向

我接触这个也比较少，你看看这个链接
[参考链接](https://blog.csdn.net/lixpjita39/article/details/89424459)
